[features]
seeds = false
skip-lint = false

[programs.devnet]
ivza_engine = "DiiCy7G6p5QVvGcAWfwA6m5EjyPeD5BRnEit9ersPUq2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/ivza-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
